"use strict";
exports.__esModule = true;
var numx;
var boolItem;
var strDat;
var car = [3, 4, "9348.33sdh", "Abhi", -3849.300, 'a', 34.004];
numx = 20.0033;
var fx = function () { return "Hello TypeScripting!! worlds.." + numx; };
console.log(fx());
console.log("\nprint arr : " + car);
console.log("\nFor Continusly comple code type script command : tsc typescriptApp.ts -watch");
console.log("\nexport{} used to remove all erros from TS file");
